### ISSUE TITLE
일렉트론 아이콘 변경

### ISSUE THREAD

**Issue by younggeun0** [younggeun0/pomodoro_notion_recorder#4]
일렉트론 기본 아이콘을 토마토로 변경

**Comment by younggeun0** [comment]
[해당 커밋](https://github.com/younggeun0/pomodoro_notion_recorder/commit/9c24cf48af30dacfa18371c9e5fc52d4f85f96f3)으로 반영완료
수고하셨습니다.

**Comment by hyeonjeongJu** [comment]
```bash
npm run build
```
- 프로젝트 소스 코드를 프로덕션 준비 형식으로 컴파일하는 데 사용 (ts > js)
```bash
npm run package --mac
```
- 배포용 애플리케이션을 패키징하는 데 사용
(필요한 리소스(예: 이미지, 스타일시트 등)를 포함하여 프런트엔드 및 백엔드 코드를 묶고 데스크톱 환경에 적합한 실행 가능한 형식으로 모든 것을 래핑)
- Electron과 같은 프레임워크를 사용하여 크로스 플랫폼 데스크톱 애플리케이션을 만드는 프로젝트에서 일반적

1. [링크](https://www.christianengvall.se/electron-app-icons/)와 같이 작업했으나 앱아이콘의 변경이 안됐음
2. `--mac` 옵션을 주니 512x512 형식의 이미지가 없어서 적용안됨을 확인
3. [지원 양식](https://www.electronforge.io/guides/create-and-add-icons#supported-formats)이 있음을 확인
